name: Android CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Bulid
      run: ./gradlew clean

    - name: Run ktlint with reviewdog

    - name: GPT PR Reviewer
      uses: galadrimteam/gpt-pr-review@1.3.3
      with:
        # Github token
        github-token: ${{ secrets.TOKEN }}
        # OpenAI GPT API key
        gpt-api-key: ${{ secrets.OPEN_API_KEY }}
          



          
